### PR TITLE
Feature/fingerprint password handling

### PR DESCRIPTION
**Pull request by hanscappelle**
I've added fingerprint support. What it does is create a key for encryption/decryption of the password field in PasswordActivity that is secured with fingerprint. Once fingerprint is used once to store an entered password using fingerprint again the next time will complete that password field with the decrypted value and open database using existing logic. 

The encrypted password is stored in app preferences with a key based on the name of the database uri (path) so should be unique for each database.

Most changes are in PasswordActivity for the logic to show/hide the fingerprint icon based on support and start listening for fingerprints and handle the encoded or decoded value. 

The newly added FingerprintHelper contains the logic for handling keystore and encryption and decryption of value with a key from that secured keystore. 

It's tested on Nexus 5X running Android 8 so might require some care on api level and other details. It works for me. If you're interested we can look into completing this implementation.

### CODE REVIEW

**Comment by Jenkyn** [comment]
I notice that you change compileSdkVersion from 22 to 23. There is an notification api, notify.setLatestEventInfo(), is called in line 236 of EntryActivity.java, is also removed from api 23. You can check it out [here](https://developer.android.com/sdk/api_diff/23/changes/android.app.Notification.html). How can you complie the code without modifing the EntryActivity class ?

**Comment by hanscappelle** [comment]
@Jenkyn Change from 22 => 23 is needed for fingerprint since that was added in 23. It still compiles on my version since I'm not using that part and only checked in the relevant changes overlooking this. From what I can find to fix it you have to create a new notification instead (preferable with compat also). Didn't realise this. Let me know if you want me to look into that.

**Comment by hanscappelle** [comment]
I've just committed a workaround for that using the NotificationCompat.Builder form support v4 libraries. I had to upgrade from minSdkVersion 3 to 4 though because of that support library. It's not tested here since I don't use that part of code.

**Comment by hanscappelle** [comment]
I've now tested multi database support (had to fix storage of IV spec for it to work) and also fixed the single runtime permission that is in place for storage.

**Comment by Jenkyn** [comment]
@hanscappelle pull your latest commit and complie, it works on my phone (Android 7.1.2).

**Comment by hanscappelle** [comment]
@Jenkyn "pull your latest commit", that's a strange thing to say :D. But good to know it works for you also. Thanks for the update 👍

**Comment by bpellin** [comment]
Thanks. My major concern that kept me from merging the other finger print support was that it didn't store a key per file. I'll take a look over this.

**Comment by hanscappelle** [comment]
Awesome!! Glad you liked it & thanks for the update. Good thing to know fingerprint has a compat implementation also.

**Pull request merged**
