### PR TITLE
Fix the OOM issue for Large attachment #287

### PR DESCRIPTION
**Pull request by J-Jamet**
Consumes serialized files (attached files) that are not used by KeePassDroid to resolve the "Out Of Memory" problem. #287

### CODE REVIEW

**Comment by bpellin** [comment]
It looks like this would result in losing any attachments upon editing your database. Is that correct?

**Comment by J-Jamet** [comment]
Unfortunately yes, we should implement a temporary file management system, I'm thinking about it.

**Comment by bpellin** [comment]
That makes sense. I have considered something similar. Perhaps the ProtectedBinary class could been extended to manage writing the contents out to a file in application specific storage.

**Comment by J-Jamet** [comment]
Yes, I was on the same idea by replacing the data property of ProtectedBinary with files. After it is necessary to manage the destruction of the files during the exit. I'm looking to implement that.
What are the benefits for you to make a single file, access will be faster?

**Comment by J-Jamet** [comment]
OK, the temp memory works fine and we keep the attached files after a change! :)

**Pull request merged**
